
name: Build and run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Setup NodeJS 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Setup Railflow CLI
      run: npm install railflow
    - name: Build with Maven
      run: mvn clean package -DskipTests
    - name: Run Cucumber tests
      run: mvn test
    - name: Export results to TestRail
      if: always()
      run: npx railflow -k LUKKL-WIGVV-IIHEL-EEQWK -url https://railflow.testrail.io -u ali.raza@railflow.io -p Goliath1! -pr "Cucumber Demo" -path All -f cucumber -r target/test-reports/cucumber.json -sm name -tp All -mp Release
